### ISSUE TITLE
Sometimes sound effects will not play

### ISSUE THREAD

**Issue by chris-wolff** [chris-wolff/java-pong#23]
Certain sound states cause an exception to be thrown or sound to cut off, completely. Related to #38

**Comment by christopher-wolff23** [comment]
Could be caused by two sounds trying to play, simultaneously.

**Comment by christopher-wolff23** [comment]
Limited to Linux, only.

**Comment by chris-wolff** [comment]
Fixed this with the strange audio code which is hard to understand and uses several different Java Sound and File classes in tandem.

**Comment by chris-wolff** [comment]
Related to

**Comment by chris-wolff** [comment]
Should be resolved for same reason #38 bug is fixed. Closed threads that were hogging lines.
