### ISSUE TITLE
"Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException"

### ISSUE THREAD

**Issue by chris-wolff** [chris-wolff/java-pong#24]
Only happens on occasional runs. Only found on Linux, thus far.

**Comment by christopher-wolff23** [comment]
Possibly occurring somewhere in the paint() method.

**Comment by mobiuscog** [comment]
It's hard to tell without the full stack trace, but there is a potential race condition where the ball is temporarily null (line 199 within the DestroyBall method) which would cause a NullPointerException if the EventQueue was painting at that time.

**Comment by chris-wolff** [comment]
Added a `null` check for the paddles in the `paint()` method with #36 but that does not address concurrency issues, completely.

**Comment by chris-wolff** [comment]
Added a lock/synchronization for both paddles. `paint()` only reads values; could potentially get some cases where `paint()` gets a score/game over state slightly late/early, but the main problem should be the `null` or `new Object()` creation being off. Don't want to overuse `synchronize`.
