### ISSUE TITLE
Mixed indent spaces and tabs

### ISSUE THREAD

**Issue by wild-mouse** [chris-wolff/java-pong#33]
I've found spaces and tabs are mixed for indents(for instance lines 56 and 57 of Game.java).
It's not a problem in editors but looks so strange in GitHub viewer.

https://github.com/chris-wolff/java-pong/blob/635c7c67d9e8ac5c7e65df4337f5b31bb4972ea3/java/Game.java#L54-L59

**Comment by chris-wolff** [comment]
@wild-mouse good find! Yes, this is an issue. If you would like to create a pull request to resolve it, that would be helpful. (I prefer tabs, but spaces are fine, too, as long as everything is uniform.)
