### ISSUE TITLE
Enemy AI is too good, too accurate. Near impossible to defeat.

### ISSUE THREAD

**Issue by chris-wolff** [chris-wolff/java-pong#9]
Implement different difficult levels? Find a way to teach the enemy paddle how to learn? Make the paddle slower (find a balanced difficulty/accuracy)?

**Comment by abrandell** [comment]
One way to make it actually beatable would be to only let the enemy paddle move once the ball has come within a certain distance.

**Comment by christopher-wolff23** [comment]
@abrandell Thanks for the suggestion!

**Comment by chris-wolff** [comment]
Used @abrandell's comment for AI, and AI becomes progressively more accurate depending on the score of the game.
